import { type NextRequest, NextResponse } from "next/server"

export async function POST(req: NextRequest) {
  try {
    const { workspace, database, projectName, documents } = await req.json()

    // In a real implementation, this would use Notion's API
    // For now, we'll simulate the page creation
    const notionPage = {
      id: `page_${Math.random().toString(36).substr(2, 9)}`,
      title: projectName,
      url: `https://notion.so/${workspace}/${projectName.replace(/\s+/g, "-")}-${Math.random().toString(36).substr(2, 6)}`,
      created_time: new Date().toISOString(),
      last_edited_time: new Date().toISOString(),
      properties: {
        Name: {
          title: [
            {
              text: {
                content: projectName,
              },
            },
          ],
        },
        Status: {
          select: {
            name: "In Progress",
          },
        },
        Created: {
          date: {
            start: new Date().toISOString().split("T")[0],
          },
        },
      },
      children: [
        {
          type: "heading_1",
          heading_1: {
            rich_text: [
              {
                text: {
                  content: "Project Overview",
                },
              },
            ],
          },
        },
        {
          type: "paragraph",
          paragraph: {
            rich_text: [
              {
                text: {
                  content: "This project documentation was automatically generated by SDLC Automation Platform.",
                },
              },
            ],
          },
        },
        {
          type: "heading_2",
          heading_2: {
            rich_text: [
              {
                text: {
                  content: "Business Analysis",
                },
              },
            ],
          },
        },
        {
          type: "paragraph",
          paragraph: {
            rich_text: [
              {
                text: {
                  content: documents?.businessAnalysis || "Business analysis content...",
                },
              },
            ],
          },
        },
        {
          type: "heading_2",
          heading_2: {
            rich_text: [
              {
                text: {
                  content: "Technical Specification",
                },
              },
            ],
          },
        },
        {
          type: "paragraph",
          paragraph: {
            rich_text: [
              {
                text: {
                  content: documents?.technicalSpec || "Technical specification content...",
                },
              },
            ],
          },
        },
      ],
    }

    return NextResponse.json({
      success: true,
      page: notionPage,
      message: "Notion page created successfully",
    })
  } catch (error) {
    console.error("Error creating Notion page:", error)
    return NextResponse.json({ error: "Failed to create Notion page" }, { status: 500 })
  }
}
