name: Claude Code Assistant
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-assist:
    if: contains(github.event.comment.body, '/claude') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Extract task from comment
        id: extract
        if: github.event_name == 'issue_comment'
        run: |
          COMMENT="${{ github.event.comment.body }}"
          TASK=$(echo "$COMMENT" | sed 's|/claude ||' | head -1)
          echo "task=$TASK" >> $GITHUB_OUTPUT
          echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT

      - name: Call Claude Cloud API
        id: claude
        uses: anthropic/claude-github-action@v1
        with:
          api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: "claude-3-5-sonnet-20241022"
          max-tokens: 4000  # Within Claude's limits
          task: ${{ steps.extract.outputs.task || 'Review this PR and suggest improvements' }}
          repository-context: true
          create-pr: true

      - name: Comment result
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.extract.outputs.issue_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🤖 Claude AI Assistant\n\n${{ steps.claude.outputs.response }}\n\n---\n*Generated by Claude 3.5 Sonnet*`
            })

      - name: Create PR if requested
        if: steps.claude.outputs.pr-url
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.extract.outputs.issue_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ✅ Task Completed\n\nClaude has created a pull request: ${{ steps.claude.outputs.pr-url }}\n\nPlease review and merge when ready.`
            }) 